import type { NextPage } from "next";
import Head from "next/head";
import { Messages } from "../components/Messages";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Acht</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>Acht!</span>
        </h1>

        <p className={styles.description}>
          Acht is a random chat service. Who knows what will happen?!
          <br />
          <i>Send a message to find out...</i>
        </p>

        <Messages />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/jamie-lynch/acht"
          target="_blank"
          rel="noopener noreferrer"
        >
          Check out Acht on GitHub!
        </a>
      </footer>
    </div>
  );
};

export default Home;
